[workspace]
resolver = "2"
members = [
    "launchpad",
    "collection_nft_erc721",
    "collection_nft_erc1155",
    "lazy_mint_erc721",
    "lazy_mint_erc1155"
]

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

[workspace.dependencies]
soroban-sdk = "25.3.0"
